In [ ]:
print("hello world")

hello world


In [ ]:
x=5
m=4
y="5"
n="6"
print(type(x))
print(type(y))
print(x+m)
print(y+n)


<class 'int'>
<class 'str'>
9
56


In [ ]:
z="4"
a=int(z)
b=a+1
print(b)

5


In [ ]:
l1 = ["hi", 0, 1.2, 3, ["ai", 12, "ds"]]
l = 1
l2 = l1[4][l]
print(l1)
print(l2)


['hi', 0, 1.2, 3, ['ai', 12, 'ds']]
12


In [ ]:
nums=[]
nums.append(21)
nums.append("hello")
nums.append(2)
print(nums)

[21, 'hello', 2]


In [ ]:
t1=(1,2,3,4,5)
print(t1)

(1, 2, 3, 4, 5)


In [ ]:
import numpy as np
arr = np.array( [[ 1, 2, 3],[ 4, 2, 5]] )
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)


Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
print("Array with Rank 1: \n",arr)
arr = np.array([[1, 2, 3],[4, 5, 6]])
print("Array with Rank 2: \n", arr)
arr = np.array((1, 3, 2))
print("\nArray created using ""passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [ ]:
import numpy as np
arr = np.array([2, 4, 6, 8, 10])
c = arr.copy()
print("id of arr", id(arr))
print("id of c", id(c))
arr[0] = 12
print("original array- ", arr)
print("copy- ", c)


id of arr 134622754913040
id of c 134622753315248
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


In [ ]:
def sum(array):
	sum = 0
	for i in array:
		sum += i
	return sum
testArray = [1, 3, 34, 92, 29, 48, 20.3]
print('The sum of your numbers is ' + str(sum(testArray)))


The sum of your numbers is 227.3


In [ ]:
import numpy as np
a = np.arange(10, 1, -2)
print("\n A sequential array with a negative step: \n",a)
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)



 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])
print ("The element wise addition of matrix is : ")
print (numpy.add(x,y))
print ("The element wise subtraction of matrix is : ")
print (numpy.subtract(x,y))
print ("The element wise division of matrix is : ")
print (numpy.divide(x,y))


The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


In [ ]:
import pandas

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pandas.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [ ]:
import pandas as pd

print(pd.__version__)

2.0.3


In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)
print(myvar[0])

0    1
1    7
2    2
dtype: int64
1


In [ ]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ["x", "y", "z"])

print(myvar)

print(myvar["y"])

x    1
y    7
z    2
dtype: int64
7


In [ ]:
import pandas as pd

data = {"calories": [420, 380, 390],"duration": [50, 40, 45]}
df = pd.DataFrame(data)
print(df)
print(df.loc[0])
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40
2       390        45
calories    420
duration     50
Name: 0, dtype: int64
   calories  duration
0       420        50
1       380        40


In [ ]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df.to_string())

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
import pandas as pd

df = pd.read_csv('Data.csv')

print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [ ]:
import pandas as pd

print(pd.options.display.max_rows)

60


In [ ]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('Data.csv')

print(df)

print(pd.options.display.max_rows)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes
9999


In [ ]:
#Load a Python Dictionary into a DataFrame   JSON= Python Dictionary
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df)


   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [ ]:
import pandas as pd
df1 = pd.DataFrame({"fruit" : ["apple", "banana", "avocado"],
					"market_price" : [21, 14, 35]})
display("The first DataFrame")
display(df1)
df2 = pd.DataFrame({"fruit" : ["banana", "apple", "avocado"],
					"wholesaler_price" : [65, 68, 75]})
display("The second DataFrame")
display(df2)
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")


'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35

'The second DataFrame'

fruit  wholesaler_price
0   banana                65
1    apple                68
2  avocado                75

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21                68
1   banana            14                65
2  avocado            35                75

In [ ]:
import pandas as pd
df1 = pd.DataFrame({"fruit" : ["apple", "banana",
                               "avocado", "grape"],
                    "market_price" : [21, 14, 35, 38]})
display("The first DataFrame")
display(df1)
df2 = pd.DataFrame({"fruit" : ["apple", "banana", "grape"],
                    "wholesaler_price" : [65, 68, 71]})
display("The second DataFrame")
display(df2)
display("The merged DataFrame")
pd.merge(df1, df2, on = "fruit", how = "inner")

pd.merge(df1, df2, on = "fruit", how = "outer")

'The first DataFrame'

fruit  market_price
0    apple            21
1   banana            14
2  avocado            35
3    grape            38

'The second DataFrame'

fruit  wholesaler_price
0   apple                65
1  banana                68
2   grape                71

'The merged DataFrame'

fruit  market_price  wholesaler_price
0    apple            21              65.0
1   banana            14              68.0
2  avocado            35               NaN
3    grape            38              71.0

In [ ]:
import pandas as pd
df = pd.read_csv("/organizations-100.csv")

print(df.head())

   Index  Organization Id                     Name  \
0      1  FAB0d41d5b5d22c              Ferrell LLC   
1      2  6A7EdDEA9FaDC52  Mckinney, Riley and Day   
2      3  0bFED1ADAE4bcC1               Hester Ltd   
3      4  2bFC1Be8a4ce42f           Holder-Sellers   
4      5  9eE8A6a4Eb96C24              Mayer Group   

                          Website           Country  \
0              https://price.net/  Papua New Guinea   
1  http://www.hall-buchanan.info/           Finland   
2       http://sullivan-reed.com/             China   
3             https://becker.com/      Turkmenistan   
4          http://www.brewer.com/         Mauritius   

                                      Description  Founded  \
0             Horizontal empowering knowledgebase     1990   
1             User-centric system-worthy leverage     2015   
2                  Switchable scalable moratorium     1971   
3  De-engineered systemic artificial intelligence     2004   
4              Synchronized needs-

In [ ]:
gk = df.groupby('Country')
gk.first()

Index  Organization Id                      Name  \
Country                                                            
Anguilla           97  BA6Cd9Dae2Efd62                  Good Ltd   
Australia          30  7Cb3AeFcE4Ba31e               Rivas Group   
Bahamas             6  cC757116fe1C085            Henry-Thompson   
Belarus            39  6883A965c7b68F7                  Hahn PLC   
Belgium            24  5Ec4C272bCf085c          Robbins-Cummings   
...               ...              ...                       ...   
Uruguay            72  adcB0afbE58bAe3                Wagner LLC   
Uzbekistan         10  738b5aDe6B1C6A5                Gaines Inc   
Vietnam            62  EB9f456e8b7022a                Soto Group   
Western Sahara     46  1eD64cFe986BBbE            Walton-Barnett   
Zimbabwe           32  f5afd686b3d05F5  Durham, Allen and Barnes   

                                      Website  \
Country                                         
Anguilla                    http://duffy.com/   
Australia                 https://hebert.org/   
Bahamas                     http://morse.net/   
Belarus                    http://newman.com/   
Belgium         http://donaldson-wilkins.com/   
...                                       ...   
Uruguay           https://decker-esparza.com/   
Uzbekistan        http://sandoval-hooper.com/   
Vietnam                  https://norris.info/   
Western Sahara   https://ashley-schaefer.com/   
Zimbabwe            http://chan-stafford.org/   

                                                 Description  Founded  \
Country                                                                 
Anguilla             Reverse-engineered composite moratorium     1971   
Australia           Open-architected well-modulated capacity     1998   
Bahamas         Face-to-face well-modulated customer loyalty     1992   
Belarus                          Organic logistical leverage     2012   
Belgium                       Organic non-volatile hierarchy     1991   
...                                                      ...      ...   
Uruguay                   Reactive attitude-oriented toolset     1987   
Uzbekistan                   Multi-lateral scalable protocol     1997   
Vietnam               Enterprise-wide executive installation     1988   
Western Sahara        Right-sized clear-thinking flexibility     2001   
Zimbabwe                   Synergistic web-enabled framework     1993   

                                             Industry  Number of employees  
Country                                                                     
Anguilla                            Consumer Services                 4292  
Australia                     Logistics / Procurement                 4155  
Bahamas                 Primary / Secondary Education                 4914  
Belarus         Electrical / Electronic Manufacturing                 3715  
Belgium                               Pharmaceuticals                 5038  
...                                               ...                  ...  
Uruguay                         International Affairs                 6874  
Uzbekistan                   Outsourcing / Offshoring                 9698  
Vietnam                 Business Supplies / Equipment                 9097  
Western Sahara                 Luxury Goods / Jewelry                 1746  
Zimbabwe         Mechanical or Industrial Engineering                 6135  

[84 rows x 8 columns]

In [ ]:
import pandas as pd
df = pd.read_csv("/nba.csv")

print(df.head())

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0  


In [ ]:
# applying groupby() function to
# group the data on team value.
gk = df.groupby('Team')

# Let's print the first entries
# in all the groups formed.
gk.first()

Name  Number Position   Age Height  \
Team                                                                          
Atlanta Hawks                   Kent Bazemore    24.0       SF  26.0    6-5   
Boston Celtics                  Avery Bradley     0.0       PG  25.0    6-2   
Brooklyn Nets                Bojan Bogdanovic    44.0       SG  27.0    6-8   
Charlotte Hornets               Nicolas Batum     5.0       SG  27.0    6-8   
Chicago Bulls                Cameron Bairstow    41.0       PF  25.0    6-9   
Cleveland Cavaliers       Matthew Dellavedova     8.0       PG  25.0    6-4   
Dallas Mavericks              Justin Anderson     1.0       SG  22.0    6-6   
Denver Nuggets                 Darrell Arthur     0.0       PF  28.0    6-9   
Detroit Pistons                  Joel Anthony    50.0        C  33.0    6-9   
Golden State Warriors         Leandro Barbosa    19.0       SG  33.0    6-3   
Houston Rockets                  Trevor Ariza     1.0       SF  30.0    6-8   
Indiana Pacers                    Lavoy Allen     5.0       PF  27.0    6-9   
Los Angeles Clippers             Cole Aldrich    45.0        C  27.0   6-11   
Los Angeles Lakers               Brandon Bass     2.0       PF  31.0    6-8   
Memphis Grizzlies                Jordan Adams     3.0       SG  21.0    6-5   
Miami Heat                         Chris Bosh     1.0       PF  32.0   6-11   
Milwaukee Bucks         Giannis Antetokounmpo    34.0       SF  21.0   6-11   
Minnesota Timberwolves        Nemanja Bjelica    88.0       PF  28.0   6-10   
New Orleans Pelicans            Alexis Ajinca    42.0        C  28.0    7-2   
New York Knicks                 Arron Afflalo     4.0       SG  30.0    6-5   
Oklahoma City Thunder            Steven Adams    12.0        C  22.0    7-0   
Orlando Magic                  Dewayne Dedmon     3.0        C  26.0    7-0   
Philadelphia 76ers                Elton Brand    42.0       PF  37.0    6-9   
Phoenix Suns                     Eric Bledsoe     2.0       PG  26.0    6-1   
Portland Trail Blazers        Cliff Alexander    34.0       PF  20.0    6-8   
Sacramento Kings                   Quincy Acy    13.0       SF  25.0    6-7   
San Antonio Spurs           LaMarcus Aldridge    12.0       PF  30.0   6-11   
Toronto Raptors               Bismack Biyombo     8.0        C  23.0    6-9   
Utah Jazz                       Trevor Booker    33.0       PF  28.0    6-8   
Washington Wizards              Alan Anderson     6.0       SG  33.0    6-6   

                        Weight                College      Salary  
Team                                                               
Atlanta Hawks            201.0           Old Dominion   2000000.0  
Boston Celtics           180.0                  Texas   7730337.0  
Brooklyn Nets            216.0         Oklahoma State   3425510.0  
Charlotte Hornets        200.0  Virginia Commonwealth  13125306.0  
Chicago Bulls            250.0             New Mexico    845059.0  
Cleveland Cavaliers      198.0           Saint Mary's   1147276.0  
Dallas Mavericks         228.0               Virginia   1449000.0  
Denver Nuggets           235.0                 Kansas   2814000.0  
Detroit Pistons          245.0                   UNLV   2500000.0  
Golden State Warriors    194.0         North Carolina   2500000.0  
Houston Rockets          215.0                   UCLA   8193030.0  
Indiana Pacers           255.0                 Temple   4050000.0  
Los Angeles Clippers     250.0                 Kansas   1100602.0  
Los Angeles Lakers       250.0                    LSU   3000000.0  
Memphis Grizzlies        209.0                   UCLA   1404600.0  
Miami Heat               235.0           Georgia Tech  22192730.0  
Milwaukee Bucks          222.0                Arizona   1953960.0  
Minnesota Timberwolves   240.0             Louisville   3950001.0  
New Orleans Pelicans     248.0             California   4389607.0  
New York Knicks          210.0                   UCLA   8000000.0  
Oklahoma City Th

In [ ]:
j = 1

while(j<= 5):
	print(j)
	j = j + 1


1
2
3
4
5
